# Generated by Django 3.0.8 on 2020-07-31 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 11, 47, 46, 396583, tzinfo=utc)),
        ),
    ]
