# Generated by Django 3.0.8 on 2020-07-31 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200731_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 12, 18, 19, 21069, tzinfo=utc)),
        ),
    ]
